### ISSUE TITLE
Mission Count

### ISSUE THREAD

**Issue by UseLessUK** [CMDR-WDX/EDMC-Massacres#18]
Would be nice if the plugin could inform you how many missions you've taken so you'll know if you're close to the limit of 20 or not.

Edit: I run EDMC + the plugin on a separate monitor so being able to see at a glance how many missions I have would be lovely.

**Comment by CMDR-WDX** [comment]
Hey @UseLessUK . I like the idea! 
Unfortunately I currently don't have Elite installed, and I don't plan to install it in the near future.
I made changes, but have not tested them. I would like to ask you to test them for me. If no issues are present I will merge it into the main branch and create a new release.

Mission count should be visible by default, with an option in the settings to disable.

I created an attached zip with this version. Alternatively, you can get the files in https://github.com/CMDR-WDX/EDMC-Massacres/tree/a4c57b8a080e8e4d8e5772a9397559681abf1075 and replace them in your Plugins folder.

[EDMC-Massacres-v2.0.5-pre1.zip](https://github.com/CMDR-WDX/EDMC-Massacres/files/11083023/EDMC-Massacres-v2.0.5-pre1.zip)

If you don't see the expected result you could send me the most recent log file. EDMC keeps a log of everything, including any errors under `%TEMP%/EDMarketConnector` (or something like that :P ).

**Comment by UseLessUK** [comment]
Thanks for the quick response :D

Tried the update and I see no count for the number of missions taken, took 3 missions from 2 factions and I see no indication of that count on the UI.

And I also don't see an option in the settings to disable the count visibility.
The only options I see on the settings tab for the plugin are;
• Display delta-column
• Display sum-row
• Display Summary-row

• Check for updates on start

**Comment by UseLessUK** [comment]
Just ignore me ... good olde User Error :D

It's working fine. And the option is now showing on the setting tab.

**Comment by CMDR-WDX** [comment]
Gotcha :D 
Let me guess… you forgot to update the plugin folder? :D

**Comment by CMDR-WDX** [comment]
alrighty.. before I forget about this… making a new version with this change :)

**Comment by CMDR-WDX** [comment]
Feature has been added as part of v2.0.5 :)
