### ISSUE TITLE
Not reading missions

### ISSUE THREAD

**Issue by towdawg** [CMDR-WDX/EDMC-Massacres#20]
There's a message on the setup page saying edmcoverlay Python Module missing. 
![Capture](https://user-images.githubusercontent.com/115946936/229402057-f6a52e6c-1ae3-4a1e-a7ec-3b5e5ab91023.JPG)

**Comment by towdawg** [comment]
Apparently that's unrelated. 
The ver of EDMC is the latest
![Capture](https://user-images.githubusercontent.com/115946936/229403868-807e4945-9923-4c27-8acb-ccc8fc8dda05.JPG)

**Comment by CMDR-WDX** [comment]
You can safely ignore the message.

An Integration is basically a plugin from this plugin. This is just a
warning that EDMC-Massacres cannot find the overlay Python Library (which
you need for the overlay on Linux, and I assume also Mac). So yeah.. If you
don't plan on enabling the overlay you can ignore it.

Are you sure about the Not Reading Missions part? I don't see anything in
this Issue about that part.

**Comment by towdawg** [comment]
With a couple CZ ship kill wing missions loaded, all it showed was the "Massacre Plugin is ready" message, so I just tried it with pirate a massacre mission and it works fine. I didn't realize the game treated the two types of combat differently. Move this to "Wishlist" along with Thargoid kill missions then and consider it resolved. Or delete it.
