### ISSUE TITLE
Feature suggestion: support for Thargoid missions

### ISSUE THREAD

**Issue by MarkusRamikin** [CMDR-WDX/EDMC-Massacres#22]
Would it be possible to count Thargoid missions the same way? They seem to also be issuable by multiple factions the same as pirates.

**Comment by CMDR-WDX** [comment]
Hey :)
In practice, it would be possible. Iirc the game does tell you the Kind of
Goid (e.g. Hydra) on the mission.
I thought about this like 8 months ago and decided not to include include
the functionality, as that would mean major changes to the way the stack is
displayed.
With Pirate Massacres it is a blunder to have Missions for different
targets. The same can't be said about goids, which would mean that you need
to display multiple tables (1 per Goid Type).

Imo it would make sense to have a separate plugin for Goid Stacking.

Am Do., 29. Feb. 2024 um 13:38 Uhr schrieb Markus Ramikin <
***@***.***>:
