### ISSUE TITLE
Some missions are missing after re-logging

### ISSUE THREAD

**Issue by Fi0x** [CMDR-WDX/EDMC-Massacres#5]
Yesterday I accepted several missions and they were displayed correctly.
When I logged back in today, only the new missions I accepted today were shown.

I have to admit that I deleted the logs from yesterday. But if it's possible, could you check the logs for already existing missions?

**Comment by CMDR-WDX** [comment]
Right now, this plugin finds Missions the following way:
- Read the last 2 weeks of Logs and collect all `MissionAccepted`-Events.
- Await the game start. The Plugin expects the `Missions` - Event which will essentially return a list of active MissionIDs. 
- Select the overlap between MissionIDs from the `Missions`-Event and the collected `MissionAccepted`-Events.

> I have to admit that I deleted the logs from yesterday

I assume you are talking about your journal files which are, by default, located in `%HOMEPATH%\Saved Games\Frontier Developments\Elite Dangerous`. The Mission Data is only stored in the `MissionAccepted` - Events. If the Journal Files are deleted, there is no way of getting those missions.

**Comment by Fi0x** [comment]
But shouldn't a journal entry get created when I open an old mission in my transactions tab?
This should contain the mission information.

If this is not the case, could you find out where the client gets the information to display in the transactions tab? Because if I deleted the journals, I have to receive the mission details from the server again.

**Comment by CMDR-WDX** [comment]
E:D keeps track of Missions internally. The relevant information is only exposed in the `MissionAccepted` Event.
Its structure can be found here: https://elite-journal.readthedocs.io/en/latest/Station%20Services/#missionaccepted

On each Startup, a Missions-Event is generated. This just holds the MissionIDs though: https://elite-journal.readthedocs.io/en/latest/Startup/#missions

> But shouldn't a journal entry get created when I open an old mission in my transactions tab?

Nope. The relevant data is written when Accepting the mission.

> If this is not the case, could you find out where the client gets the information to display in the transactions tab? Because if I deleted the journals, I have to receive the mission details from the server again.

This will be functionality that is not exposed via the Journal API. E:D does not read the Mission Data from the Logs. If that would be the case, what would me stop from setting the reward to some high number? :stuck_out_tongue:

**Comment by Fi0x** [comment]
In that case this issue is not fixable with the current APIs.
