### ISSUE TITLE
Kill-Counter

### ISSUE THREAD

**Issue by Fi0x** [CMDR-WDX/EDMC-Massacres#6]
Could you add a kill counter that tells you how much kills you have left? (If the journals even contain that information)

**Comment by chennin** [comment]
Similar to https://github.com/lunarplasma/EDMC-CombatTracker/issues/20, this could be done by counting Bounty events.

```{ "timestamp":"2021-04-21T18:24:46Z", "event":"Bounty", "Rewards":[ { "Faction":"LHS 1358 Fortune Group", "Reward":70245 } ], "Target":"federation_dropship", "Target_Localised":"Federal Dropship", "TotalReward":70245, "VictimFaction":"LHS 1358 Jet Gang", "SharedWithOthers":2 }```
